name: AOSP Clang

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    container: 
      image: zycromerz/kerneldocker:v3

    steps:
    - uses: actions/checkout@v2
    - name: Clang Cloning
      env:
        GITLAB_TOKEN@_EMAIL: ${{ secrets.GITLAB_TOKEN@_EMAIL }}
        GITLAB_TOKEN@_USERNAME: ${{ secrets.GITLAB_TOKEN@_USERNAME }}
        GITLAB_TOKEN@_TOKEN: ${{ secrets.GITLAB_TOKEN@_TOKEN }}
        GITLAB_TOKEN@_PUSH_REPO_URL: ${{ secrets.GITLAB_TOKEN@_PUSH_REPO_URL }}
      run: |
        bash goClone
